name: release

on:
  release:
    types:
      - created

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Version
      run: echo "RELEASE_VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV

    - name: Build and Release
      env:
        FORCE_COLOR: 3
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
      run: npx zx .github/workflows/release.mjs
